var_welcome_words = [
    "hi",
    "hello",
    "hello from the other side",
    "hello from the other side, I must've called you thousand time to tell you hello",
    "hey",
    "hola",
    "hello there",
    "howdy",
    "greetings",
    "bonjour",
    "whatsup",
    "yo",
    "yello",
    "yeallo",
    "konichiwa\n(hello in japanese)",
    "konnichiwa\n(hello in japanese)",
    "wassup",
    "oh, finally it's been a while",
    "glad to hear from ya",
    "sup, dawg",
    "so good to see you here!",
    "sup",
]

var_inspire_words = [
    "depressed",
    "inspire",
    "disappointed",
    "depress",
    "inspired",
    "motivated",
    "motivate",
    "unhappy",
    "sorrowful",
    "sorrow",
    "regret",
    "miserable",
    "downhearted",
    "despairing",
]

var_eight_ball_replies = [
    "It is certain.",
    "It is decidedly so.",
    "Without a doubt.",
    "Yes - definitely.",
    "You may rely on it.",
    "As I see it, yes.",
    "Most likely.",
    "Outlook good.",
    "Yes.",
    "Signs point to yes.",
    "Reply hazy, try again.",
    "Ask again later.",
    "Better not tell you now.",
    "Cannot predict now.",
    "Concentrate and ask again.",
    "Don't count on it.",
    "My reply is no.",
    "My sources say no.",
    "Outlook not so good.",
    "Very doubtful."
]
